## Application
spring.application.name=movieTicketBookingSystem

## Log file properties
## user log properties
userLog.file.path=src/main/java/com/example/movieticketbookingsystem/LoggerDB/UserLog.txt

## Date and time format
log.date.format=yyyy-MM-dd HH:mm:ss

## Database log properties
DBLog.file.path=src/main/java/com/example/movieticketbookingsystem/LoggerDB/DatabaseLogger.txt