## Application
spring.application.name=movieTicketBookingSystem

## Log file properties
userLog.file.path=src/main/java/com/example/movieticketbookingsystem/LoggerDB/UserLog.txt
log.date.format=yyyy-MM-dd HH:mm:ss